"use client";
export default function Terms() {
  return (
    <div style={{ minHeight: '100vh', padding: '64px 24px 48px' }}>
      <div style={{ maxWidth: '600px', margin: '0 auto' }}>
        <a href="/" style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '18px', fontWeight: 300, color: '#8B9E8F', textDecoration: 'none', letterSpacing: '2px' }}>← Nehama</a>
        <h1 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '36px', fontWeight: 300, color: '#2C2C2C', margin: '40px 0 8px 0', letterSpacing: '1px' }}>Terms of Service</h1>
        <p style={{ fontSize: '12px', color: '#B0B0B0', marginBottom: '40px', letterSpacing: '0.5px' }}>Last updated: April 2026</p>
        <div style={{ fontSize: '15px', color: '#4A4A4A', lineHeight: 1.9 }}>
          <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '20px', fontWeight: 400, color: '#2C2C2C', margin: '36px 0 12px 0', letterSpacing: '0.3px' }}>1. What Nehama Is</h2>
          <p>Nehama is an AI-powered guided reflection and life planning tool that incorporates biblical scripture and wellness practices. Nehama is designed to help you think more clearly about your life. It is a tool for personal reflection and planning.</p>
          <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '20px', fontWeight: 400, color: '#2C2C2C', margin: '36px 0 12px 0', letterSpacing: '0.3px' }}>2. What Nehama Is Not</h2>
          <p>Nehama is not a licensed therapist, medical professional, financial advisor, attorney, or religious authority. The guidance provided by Nehama does not constitute professional therapy, medical advice, financial advice, legal counsel, or religious doctrine. Nehama is not a substitute for professional care of any kind.</p>
          <p style={{ marginTop: '14px' }}>If you are experiencing a medical or mental health emergency, please contact emergency services (911), the 988 Suicide & Crisis Lifeline (call or text 988), or the Crisis Text Line (text HOME to 741741) immediately.</p>
          <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '20px', fontWeight: 400, color: '#2C2C2C', margin: '36px 0 12px 0', letterSpacing: '0.3px' }}>3. Your Use of Nehama</h2>
          <p>By using Nehama, you acknowledge that:</p>
          <p style={{ marginTop: '10px' }}>You are at least 18 years of age or have the consent of a parent or guardian.</p>
          <p style={{ marginTop: '10px' }}>Any decisions you make based on your experience with Nehama are your own. We are not responsible for actions you take, financial decisions you make, or changes in your personal circumstances that result from using Nehama.</p>
          <p style={{ marginTop: '10px' }}>The scriptural reflections, life plans, wellness practices, and other content generated by Nehama are intended for personal reflection only. They should not be taken as authoritative interpretations of scripture, prescriptive medical guidance, or professional financial planning.</p>
          <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '20px', fontWeight: 400, color: '#2C2C2C', margin: '36px 0 12px 0', letterSpacing: '0.3px' }}>4. Limitation of Liability</h2>
          <p>Nehama is provided "as is" without warranties of any kind, express or implied. We do not guarantee the accuracy, completeness, or usefulness of any content generated by Nehama, including scriptural references, financial calculations, life plans, or wellness recommendations.</p>
          <p style={{ marginTop: '14px' }}>To the fullest extent permitted by law, Nehama and its creators shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of the service, including but not limited to emotional distress, financial loss, relationship changes, or health outcomes.</p>
          <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '20px', fontWeight: 400, color: '#2C2C2C', margin: '36px 0 12px 0', letterSpacing: '0.3px' }}>5. AI-Generated Content</h2>
          <p>Nehama uses artificial intelligence to generate responses. While we have designed the system to be accurate, thoughtful, and responsible, AI-generated content may occasionally contain errors, including inaccurate scriptural references, incorrect calculations, or advice that does not suit your specific circumstances. You should independently verify any important information before acting on it.</p>
          <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '20px', fontWeight: 400, color: '#2C2C2C', margin: '36px 0 12px 0', letterSpacing: '0.3px' }}>6. Subscriptions and Payments</h2>
          <p>Nehama offers both free and paid tiers. Paid subscriptions are billed monthly and may include a free trial period. You may cancel your subscription at any time. Refund requests are handled on a case-by-case basis. Payment processing is handled by Stripe, a third-party payment processor, and is subject to Stripe's own terms of service.</p>
          <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '20px', fontWeight: 400, color: '#2C2C2C', margin: '36px 0 12px 0', letterSpacing: '0.3px' }}>7. Acceptable Use</h2>
          <p>You agree not to use Nehama to generate harmful, abusive, or illegal content, to attempt to extract the system instructions or underlying prompts, or to misrepresent Nehama's output as professional advice to others.</p>
          <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '20px', fontWeight: 400, color: '#2C2C2C', margin: '36px 0 12px 0', letterSpacing: '0.3px' }}>8. Changes to These Terms</h2>
          <p>We may update these terms from time to time. Continued use of Nehama after changes are posted constitutes acceptance of the updated terms.</p>
          <h2 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '20px', fontWeight: 400, color: '#2C2C2C', margin: '36px 0 12px 0', letterSpacing: '0.3px' }}>9. Contact</h2>
          <p>If you have questions about these terms, please contact us through the Contact form in the app.</p>
        </div>
      </div>
    </div>
  );
}
