"use client";
import { useState, useEffect } from "react";

const content = {
  en: {
    back: '← Nehama',
    title: 'Terms of Service',
    updated: 'Last updated: April 2026',
    sections: [
      { h: '1. What Nehama Is', p: 'Nehama is an AI-powered guided reflection and life planning tool that incorporates biblical scripture and wellness practices. Nehama is designed to help you think more clearly about your life. It is a tool for personal reflection and planning.' },
      { h: '2. What Nehama Is Not', p: 'Nehama is not a licensed therapist, medical professional, financial advisor, attorney, or religious authority. The guidance provided by Nehama does not constitute professional therapy, medical advice, financial advice, legal counsel, or religious doctrine. Nehama is not a substitute for professional care of any kind.', p2: 'If you are experiencing a medical or mental health emergency, please contact emergency services (911), the 988 Suicide & Crisis Lifeline (call or text 988), or the Crisis Text Line (text HOME to 741741) immediately.' },
      { h: '3. Your Use of Nehama', p: 'By using Nehama, you acknowledge that you are at least 18 years of age or have the consent of a parent or guardian. Any decisions you make based on your experience with Nehama are your own. We are not responsible for actions you take, financial decisions you make, or changes in your personal circumstances that result from using Nehama. The scriptural reflections, life plans, wellness practices, and other content generated by Nehama are intended for personal reflection only.' },
      { h: '4. Limitation of Liability', p: 'Nehama is provided "as is" without warranties of any kind, express or implied. We do not guarantee the accuracy, completeness, or usefulness of any content generated by Nehama, including scriptural references, financial calculations, life plans, or wellness recommendations. To the fullest extent permitted by law, Nehama and its creators shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of the service.' },
      { h: '5. AI-Generated Content', p: 'Nehama uses artificial intelligence to generate responses. While we have designed the system to be accurate, thoughtful, and responsible, AI-generated content may occasionally contain errors, including inaccurate scriptural references, incorrect calculations, or advice that does not suit your specific circumstances. You should independently verify any important information before acting on it.' },
      { h: '6. Subscriptions and Payments', p: 'Nehama offers both free and paid tiers. Paid subscriptions are billed monthly and may include a free trial period. You may cancel your subscription at any time. Refund requests are handled on a case-by-case basis. Payment processing is handled by Stripe, a third-party payment processor, and is subject to Stripe\'s own terms of service.' },
      { h: '7. Acceptable Use', p: 'You agree not to use Nehama to generate harmful, abusive, or illegal content, to attempt to extract the system instructions or underlying prompts, or to misrepresent Nehama\'s output as professional advice to others.' },
      { h: '8. Changes to These Terms', p: 'We may update these terms from time to time. Continued use of Nehama after changes are posted constitutes acceptance of the updated terms.' },
      { h: '9. Contact', p: 'If you have questions about these terms, please contact us through the Contact form in the app.' },
    ]
  },
  es: {
    back: '← Nehama',
    title: 'Términos de Servicio',
    updated: 'Última actualización: Abril 2026',
    sections: [
      { h: '1. Qué es Nehama', p: 'Nehama es una herramienta de reflexión guiada y planificación de vida impulsada por inteligencia artificial que incorpora escrituras bíblicas y prácticas de bienestar. Nehama está diseñada para ayudarte a pensar con más claridad sobre tu vida. Es una herramienta para la reflexión personal y la planificación.' },
      { h: '2. Qué no es Nehama', p: 'Nehama no es un terapeuta licenciado, profesional médico, asesor financiero, abogado ni autoridad religiosa. La orientación proporcionada por Nehama no constituye terapia profesional, consejo médico, asesoramiento financiero, consejo legal ni doctrina religiosa. Nehama no es un sustituto de la atención profesional de ningún tipo.', p2: 'Si estás experimentando una emergencia médica o de salud mental, por favor contacta a los servicios de emergencia (911), la Línea de Crisis 988 (llama o envía un mensaje de texto al 988), o la Línea de Texto de Crisis (envía HOME al 741741) inmediatamente.' },
      { h: '3. Tu uso de Nehama', p: 'Al usar Nehama, reconoces que tienes al menos 18 años de edad o tienes el consentimiento de un padre o tutor. Cualquier decisión que tomes basada en tu experiencia con Nehama es tuya. No somos responsables de las acciones que tomes, las decisiones financieras que hagas, o los cambios en tus circunstancias personales que resulten del uso de Nehama. Las reflexiones bíblicas, planes de vida, prácticas de bienestar y otro contenido generado por Nehama están destinados únicamente para reflexión personal.' },
      { h: '4. Limitación de Responsabilidad', p: 'Nehama se proporciona "tal cual" sin garantías de ningún tipo, expresas o implícitas. No garantizamos la exactitud, integridad o utilidad de ningún contenido generado por Nehama. En la máxima medida permitida por la ley, Nehama y sus creadores no serán responsables de ningún daño directo, indirecto, incidental, consecuente o especial que surja de tu uso del servicio.' },
      { h: '5. Contenido Generado por IA', p: 'Nehama utiliza inteligencia artificial para generar respuestas. Aunque hemos diseñado el sistema para ser preciso, reflexivo y responsable, el contenido generado por IA puede contener errores ocasionalmente, incluyendo referencias bíblicas inexactas, cálculos incorrectos o consejos que no se ajusten a tus circunstancias específicas. Debes verificar independientemente cualquier información importante antes de actuar sobre ella.' },
      { h: '6. Suscripciones y Pagos', p: 'Nehama ofrece niveles gratuitos y de pago. Las suscripciones pagas se facturan mensualmente y pueden incluir un período de prueba gratuito. Puedes cancelar tu suscripción en cualquier momento. Las solicitudes de reembolso se manejan caso por caso. El procesamiento de pagos es manejado por Stripe y está sujeto a sus propios términos de servicio.' },
      { h: '7. Uso Aceptable', p: 'Aceptas no usar Nehama para generar contenido dañino, abusivo o ilegal, intentar extraer las instrucciones del sistema o los prompts subyacentes, o tergiversar la salida de Nehama como consejo profesional a otros.' },
      { h: '8. Cambios a Estos Términos', p: 'Podemos actualizar estos términos de vez en cuando. El uso continuado de Nehama después de que se publiquen los cambios constituye la aceptación de los términos actualizados.' },
      { h: '9. Contacto', p: 'Si tienes preguntas sobre estos términos, por favor contáctanos a través del formulario de contacto en la aplicación.' },
    ]
  }
};

export default function Terms() {
  const [lang, setLang] = useState('en');
  useEffect(() => { const saved = localStorage.getItem('nehama-lang'); if (saved) setLang(saved); }, []);
  const c = content[lang];
  const hStyle = { fontFamily: "'Cormorant Garamond', serif", fontSize: '20px', fontWeight: 400, color: '#2C2C2C', margin: '36px 0 12px 0', letterSpacing: '0.3px' };
  return (
    <div style={{ minHeight: '100vh', padding: '64px 24px 48px' }}>
      <div style={{ maxWidth: '600px', margin: '0 auto' }}>
        <a href="/" style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '18px', fontWeight: 300, color: '#8B9E8F', textDecoration: 'none', letterSpacing: '2px' }}>{c.back}</a>
        <h1 style={{ fontFamily: "'Cormorant Garamond', serif", fontSize: '36px', fontWeight: 300, color: '#2C2C2C', margin: '40px 0 8px 0', letterSpacing: '1px' }}>{c.title}</h1>
        <p style={{ fontSize: '12px', color: '#B0B0B0', marginBottom: '40px', letterSpacing: '0.5px' }}>{c.updated}</p>
        <div style={{ fontSize: '15px', color: '#4A4A4A', lineHeight: 1.9 }}>
          {c.sections.map((s, i) => (
            <div key={i}>
              <h2 style={hStyle}>{s.h}</h2>
              <p>{s.p}</p>
              {s.p2 && <p style={{ marginTop: '14px' }}>{s.p2}</p>}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
